name: Build UniTime with Ant

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: unitime

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Ant
      run: |
        sudo apt-get update
        sudo apt-get install -y ant

    - name: Build CPSolver with Ant (if exists)
      run: |
        cd unitime
        if [ -d "CPSolver" ]; then
          cd CPSolver
          ant
          cd ..
        else
          echo "CPSolver directory not found, skipping CPSolver build."
        fi

    - name: Build UniTime with Ant
      run: |
        cd unitime
        ant

    - name: Debug on Failure
      if: failure()
      run: |
        cd unitime
        ant -debug -verbose
