name: Build UniTime with CPSolver

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build CPSolver Module
      run: |
        if [ -d "CPSolver" ]; then
          cd CPSolver
          mvn clean install -DskipTests
          cd ..
        else
          echo "CPSolver directory not found, please check the repository structure."
          exit 1
        fi

    - name: Build UniTime
      run: mvn clean install -DskipTests

    - name: Run Tests
      run: mvn test

    - name: Debug on Failure
      if: failure()
      run: mvn clean install -e -X
