name: Build UniTime

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Configure Maven Repositories
      run: |
        echo '<settings>
          <profiles>
            <profile>
              <id>unitime</id>
              <repositories>
                <repository>
                  <id>central</id>
                  <url>https://repo.maven.apache.org/maven2</url>
                  <releases><enabled>true</enabled></releases>
                  <snapshots><enabled>false</enabled></snapshots>
                </repository>
                <repository>
                  <id>unitime-repo</id>
                  <url>https://www.unitime.org/repo</url>
                  <releases><enabled>true</enabled></releases>
                  <snapshots><enabled>true</enabled></snapshots>
                </repository>
              </repositories>
              <pluginRepositories>
                <pluginRepository>
                  <id>central</id>
                  <url>https://repo.maven.apache.org/maven2</url>
                  <releases><enabled>true</enabled></releases>
                  <snapshots><enabled>false</enabled></snapshots>
                </pluginRepository>
                <pluginRepository>
                  <id>unitime-repo</id>
                  <url>https://www.unitime.org/repo</url>
                  <releases><enabled>true</enabled></releases>
                  <snapshots><enabled>true</enabled></snapshots>
                </pluginRepository>
              </pluginRepositories>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>unitime</activeProfile>
          </activeProfiles>
        </settings>' > ~/.m2/settings.xml

    - name: Build UniTime
      run: mvn clean install -DskipTests

    - name: Run Tests
      run: mvn test

    - name: Debug on Failure
      if: failure()
      run: mvn clean install -e -X
