name: Build UniTime

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      # بیلد و نصب cpsolver
      - name: Build cpsolver
        run: |
          cd cpsolver
          mvn clean install -DskipTests

      # بیلد کل UniTime بعد از نصب cpsolver
      - name: Build UniTime
        run: mvn clean package -DskipTests

      # آپلود خروجی war
      - name: Upload WAR
        uses: actions/upload-artifact@v4
        with:
          name: unitime-war
          path: target/unitime-*.war
